export const defaultRow = {
    equipmentCosts: 0,
    estimatedProfit: 0,
    machineOperatorSalary: 0,
    mainCosts: 0,
    materials: 0,
    mimExploitation: 0,
    overheads: 0,
    parentId: null,
    rowName: '',
    salary: 0,
    supportCosts: 0,
    id: 0,
    total: 0,
}